inputs:
  invoker-email:
    description: 'invoker email'
  message:
    description: 'message to publish'
runs:
  using: 'composite'
  steps:
    - name: Get slack user information
      id: slack-info
      shell: bash
      run: |
        slack_user_id=$(wget -q -O - --header="Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" "https://slack.com/api/users.lookupByEmail?email=${{ inputs.invoker_email }}" | jq .user.id)
        echo "::set-output name=slack-user-id::${slack_user_id}"
    - name: Notify
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        mention: ${{  steps.slack-info.outputs.slack-user-id }} 
        if_mention: 'always'
        test: ${{  steps.slack-info.outputs.slack-user-id }} 
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
